port=0
interface=veth-ns
bind-interfaces
dhcp-authoritative
dhcp-range=192.168.50.100,192.168.50.150,255.255.255.0,12h
dhcp-option=option:router,192.168.50.1
dhcp-option=option:dns-server,192.168.50.1
dhcp-option=option:domain-name,aichi.example
log-dhcp
