reporting-disabled = true

[meta]
  dir = "/tmp/influxdb/meta"

[data]
  dir = "/tmp/influxdb/data"
  wal-dir = "/tmp/influxdb/wal"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = false
