name: nmap

on: [push, workflow_dispatch]

jobs:
  scan:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/universal:2-linux
    steps:
      - uses: actions/checkout@v4
      - run: bash setup.sh
      - run: bash test.sh
